name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.18" ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49
